[workspace]

members = [
    "crates/client",
    "crates/icd",
    "crates/server",

    "pc-examples/client-tcp",
    "pc-examples/server-tcp",
    "pc-examples/component-spi-tcp",
    "pc-examples/arbitrator-spi-tcp",

    "spi",
]
